### ISSUE TITLE
2Checkout Sandbox credentials

### ISSUE THREAD

**Issue by yazinsai** [2Checkout/php-examples#1]
Where can I get my sandbox credentials (`sandbox-private-key` and `sandbox-seller-id`)?
I can't find them anywhere in the 2Checkout Dashboard.. and using the production credentials results in an `Unauthorized` error.

**Comment by pankaj-sachdeva** [comment]
Hi yazinsai, you can find 'sandbox-seller-id (account number)' on the top right corner, there is a user image. There is 'Account Name, Account Name and Username' info available.

To get  'sandbox-private-key & publishable key', click on API menu. It redirects you to 'Terms and condition page'. Accept the terms and conditions by clicking the checkbox and continue. This will generate both the keys.
