### ISSUE TITLE
Works better in sandbox but not live

### ISSUE THREAD

**Issue by Ephra** [2Checkout/php-examples#3]
Hello
I have done a pretty job in sandbox account, it went well and all payments was successful, but when I switch to live account, and change only username,password and keys, it does not work at all. The authorization went fine but card cannot be charged. What could be the issue please ?

These are parameters I pass

```
`  $param = array(
        "merchantOrderId" => 12453 //we can pass INVOICE later
        "token" => $request('token'),
        "currency" => 'USD',
        "total" => $total,
        "lineItems"=>array(
            "type"=>"coupon",
            "name"=>'contribution',
            "price"=>$total,
            'tangible'=>'N',
            'startupFee'=>0,
            'quantity'=>1
        ),
        "billingAddr" => array(
            "name" => $client->firstname . ' ' . $client->lastname,
            "addrLine1" => '123 Mikocheni B Street',
            "city" => 'Dar es salaam',
            "state" => 'TZ',
            "zipCode" => '255',
            "country" => $client->country_name,
            "email" => $client->email,
            "phoneNumber" => $client->phone_number,
        ));`
```

The error message I got is "Unable to process the request". Any help please, I will appreciate

**Comment by craigchristenson** [comment]
From looking at the payload, one issue appears be that you are placing a sale for 0.00 which is not allowed through 2Checkout. Also you should only be passing either the `total` parameter or `lineItems`, not both. If you remove the `lineitems` array and just pass `total` the sale should go through.
